### ISSUE TITLE
Hide yaml container instead of 

### ISSUE THREAD

**Issue by chuckharmston** [hua03/obsidian-toggle-meta-yaml-plugin#3]
Now that the Obsidian 1.1.9 installer supports `:has`, this plugin can hide the `.cm-line`'s container, preventing the extra blank line that previously caused problems:

```css
.toggle-meta-yaml--hide .cm-line:has(.cm-hmd-frontmatter) {
    display: none;
}
```
